name: 🐧 Linux CLI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-cli:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: czkawka_cli-linux-amd64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: czkawka_cli-linux-arm64 
        toolchain: [ stable ]
        type: [ release ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Pull czkawka
        run: |
            git clone  -b json_ouput https://github.com/wuxingzhong/czkawka.git

      - name: Install basic libraries
        run: sudo apt-get update; sudo apt install libheif-dev ffmpeg -y

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build Release
        run:  |
          cd czkawka 
          cargo build --release --bin czkawka_cli --target ${{ matrix.target }}
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0"
        if: ${{ (matrix.type == 'release') }}

      - name: Store Linux CLI
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: czkawka/target/release/czkawka_cli
        if: ${{ matrix.type == 'release' }}
