name: 🐧 Linux CLI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-cli:
    strategy:
      matrix:
        toolchain: [ 1.70.0 ]
        type: [ release ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Pull czkawka
        run: |
            git clone  -b json_ouput https://github.com/wuxingzhong/czkawka.git

      - name: Install basic libraries
        run: sudo apt-get update; sudo apt install libheif-dev ffmpeg -y

      - name: Setup rust version
        run: rustup default ${{ matrix.toolchain }}

      - name: Build Release
        run:  |
          cd czkawka 
          cargo build --release --bin czkawka_cli
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0"
        if: ${{ (matrix.type == 'release') }}

      - name: Store Linux CLI
        uses: actions/upload-artifact@v3
        with:
          name: czkawka_cli-${{ runner.os }}-${{ matrix.toolchain }}
          path: czkawka/target/release/czkawka_cli
        if: ${{ matrix.type == 'release' }}
